name: TSVerificationChecker
main: com.publicuhc.tsverificationchecker.VerificationCheckerPlugin
version: 1.0
description: Check if players are verified/online in Teamspeak
author: ghowden/Eluinhost
database: false
commands:
  tsverify:
    description: Check verification/online status of a player/s
      usage: /<command true/false player1 player2 player3 ... OR /<command> true/false *
      aliases: [tsverifycheck]
permissions:
  tsverify.command:
    description: Allows use of the tsverify command
    default: op